[project]
name = "appli-st-fpi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "streamlit<1.40",
    "pandas",
    "pygwalker",
    "pyinstaller",
    "scikit-learn",
    "matplotlib",
    "numpy",
    "plotly",
    "seaborn",
    "joblib",
    "xgboost-cpu",
    "tornado",
]
